---
- name: create virtual private gateway
  command: aws ec2 create-vpn-gateway --type ipsec.1 --query VpnGateway.VpnGatewayId --output text
  register: vpg_id

- name: create a tag for customer gateway
  command: aws ec2 create-tags --resources {{ vpg_id.stdout }} --tags Key=Name,Value={{ vpg_name }}

- name: output virtual private gateway id
  debug: 
    msg: "{{ vpg_id.stdout }}"

- name: add vpg id in parameter file
  lineinfile: dest={{ playbook_dir }}/state_file line="vpg_id={{ vpg_id.stdout }}"

- name: attach vpg to vpc
  command: aws ec2 attach-vpn-gateway --vpn-gateway-id {{ vpg_id.stdout }} --vpc-id {{ vpc_var.vpc.id }} --query VpcAttachment.State --output text
  register: vpg_vpc_state

- name: output vpg attachment state
  debug:
    msg: "{{ vpg_vpc_state.stdout }}"

