---
- name: Wait until connection is available on ec2 instance
  win_ping:
  register: res_ping
  until: res_ping.ping == "pong"
  retries: 100
  delay: 10

- name: install ADDS
  win_feature:
    name: "AD-Domain-Services"
    state: present
    restart: yes
    include_sub_features: yes
    include_management_tools: yes

- name: open port on firewall
  raw: 'netsh advfirewall firewall add rule Profile=domain name="Allow WinRM HTTPS" d=in localport=5986 protocol=TCP action=allow'

- name: copy script file
  local_action: template src=Install-ADDSForest.ps1.j2 dest=./Install-ADDSForest.ps1

- name: run script to install ADDSForest
  script: 'Install-ADDSForest.ps1'
